### ISSUE TITLE
The original extension "Alternate Player for Twitch.tv" (Twitch 5) is available in the Google Web Store

### ISSUE THREAD

**Issue by CoolCmd** [kurtextrem/Twitch5#4]
@kurtextrem, I sent a review of your extension to the Web Store. Here it is:
____________
The original extension "Alternate Player for Twitch.tv" (Twitch 5) is available in the Google Web Store at the new address https://chrome.google.com/webstore/detail/bhplkbgoehhhddaoolmakpocnenplmhf
So I think that this extension (Improved Player for Twitch) is no longer needed?

kurtextrem, thanks for porting the extension! But porting from the Firefox version has serious disadvantages:

* CSS does not work properly. For example, I can not change the size of the player interface. Also, huge "paddings", missing `<select>` styling, etc.

* Firefox version (and Edge version) has diffirences in the video playback logic. Therefore, in Chrome there may be problemps with the video.

* There is other differences, for example in memory management.
____________

I suggest to post news (in news.js), so that your extension's users know about my new extension. I can create pull request to modify `news.js` and `messages.json`.

**Comment by kurtextrem** [comment]
Hi Alexander! Really nice to see you back.

Sure, I take your PR!

Also note, I have made a few customizations, e.g. I've enabled `use asm` in Chrome!
I've also added a few css tweaks to further reduce RAM consumption of the page and to improve the Layers of the site.

Commits here: 
https://github.com/kurtextrem/Twitch5/commit/58f65948e1e26c417778aaeca57e6f529835ea66
https://github.com/kurtextrem/Twitch5/commit/9c5252769150558b394e44fb7a95ef9f8241bab4
https://github.com/kurtextrem/Twitch5/commit/31f8ea72afadb2ceb618d9ca8572e00f0ea7b15b
https://github.com/kurtextrem/Twitch5/commit/25ca325cb5b21cb1e97fae8d202c9d5f1ef93fe1#diff-a9b24acc6c8d37de23098caa2f7907da (higher JS perf)
https://github.com/kurtextrem/Twitch5/commit/5f5b3be3c8cf8f9252c1d8fba899596db5fde75d#diff-453065f2c559fbe22d8c17b5ba52a1b8 animations instead of `visibility: hidden` (so `display: none` can be used)

**Comment by CoolCmd** [comment]
> Sure, I take your PR!

First, decide whether you will continue to support your version (I do not know why). If not, I will change the extension so that player always displays the message stating that the extension is no longer supported, and original extension is located at the new address. In a month, when the extension is updated for all users, it can be hidden in the Web Store.

> I've enabled use asm in Chrome!

Why did you decide that the Cyrillic characters prevent ASM from working? Have you read my //comments?

> I've also added a few css tweaks to further reduce RAM consumption of the page and to improve the Layers of the site.

Do you see any improvements in the profiler? I do not think that these changes can reduce RAM.

**Comment by kurtextrem** [comment]
I will of course stop development of "my" version (it's yours of course). Can you create the PR? I'll happily merge and release (I've unlisted it already from the Webstore and updated the description).

> Why did you decide that the Cyrillic characters prevent ASM from working? Have you read my //comments?
I got a warning in the Chrome Devtools, after I've replaced all Cyrillic characters I did not get those warnings anymore.
Also, I didn't read your // comments, as I can't speak Russian (I'm German).

> Do you see any improvements in the profiler? I do not think that these changes can reduce RAM.

See here: 
Your version
![screenshot_25](https://user-images.githubusercontent.com/502146/37174287-586f69ce-2316-11e8-9ff4-30ac4d0e3579.png)
![screenshot_27](https://user-images.githubusercontent.com/502146/37174288-59f72aa2-2316-11e8-9e62-f38c2f1cea0c.png)

My changes
![screenshot_29](https://user-images.githubusercontent.com/502146/37174313-6b1ae8dc-2316-11e8-8779-2a5dd6e1b601.png)

See the div layer, it's muuuuuch smaller.
